wordsFromDict = {
    "amor": "amorphous",
    "ang": "angular",
    "anh": "anhydrite",
    "arg": "argillaceous",
    "blk": "black",
    "blky": "blocky",
    "blsh": "bluish",
    "brn": "brown",
    "calc": "calcareous",
    "cmt": "cement",
    "cmtd": "cemented",
    "chky": "chalky",
    "crs": "coarse",
    "clss": "colorless",
    "cmpct": "compact",
    "cmpctd": "compacted",
    "consld": "consolidated",
    "crmy": "creamy",
    "crpxln": "cryptocrystalline",
    "cut": "cut",
    "dk": "dark",
    "dol": "dolomite",
    "dolic": "dolomitic",
    "f": "fine",
    "frm": "firm",
    "fiss": "fissile",
    "flor": "florescence",
    "fm": "formation",
    "fri": "friable",
    "glauc": "glauconitic",
    "grdg": "grading",
    "gn": "grain",
    "gy": "gray",
    "gysh": "grayish",
    "grnsh": "greenish",
    "grs": "grains",
    "hd": "hard",
    "hily": "highly",
    "ind": "indurated",
    "kao": "kaolinite",
    "kaoic": "kaoliniteic",
    "it": "light",
    "lt": "light",
    "lst": "limestone",
    "lse": "loose",
    "mrl": "marl",
    "m": "medium",
    "med": "medium",
    "mic": "micaceous",
    "micxln": "microcrystalline",
    "mlky": "milky",
    "modly": "moderately",
    "non": "non",
    "no": "no",
    "off": "off",
    "occly": "occasionally",
    "obm": "obm",
    "opq": "opaque",
    "pa": "pale",
    "pstd": "pasted",
    "p": "poor",
    "ply": "poorly",
    "por": "porosity",
    "pyre": "pyritic",
    "qtz": "quartz",
    "rdsh": "reddish",
    "resdl": "residual",
    "rng": "ring",
    "rnd": "rounded",
    "s": "shows",
    "snd": "sand",
    "sst": "sandstone",
    "sh": "shale",
    "silc": "siliceous",
    "sltst": "siltstone",
    "silty": "silty",
    "slty": "slaty",
    "slly": "slightly",
    "slw": "slow",
    "smky": "smoky",
    "sft": "soft",
    "srtd": "sorted",
    "stky": "sticky",
    "strmng": "streaming",
    "sb": "sub",
    "suc": "sucrosic",
    "tansh": "tannish",
    "tex": "texture",
    "tr": "traces",
    "trnsl": "translucent",
    "trnsp": "transparent",
    "v": "very",
    "vf": "very fine",
    "vis": "visible",
    "vugy": "vuggy",
    "wshble": "washable",
    "w": "well",
    "wh": "white",
    "yel": "yellow",
    "yelsh": "yellowish",
    "i/p": "in_parts",
    "n/s": "no_shows",
    "dash": "to",  # "-"
    "w_": "with",  # "/"
}

specialWordsFromDict = {
    "in_part": "in part",
    "no_shows": "no shows",
    "NO_SHOWS": "NO SHOWS",
    "-": " dash ",
    "w/": "w_"
}
